apiVersion: v1
kind: Secret
metadata:
    name: my-private-ssh-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    url: git@gitlab.com:Traianik/mypy-terraform.git
    sshPrivateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        #TODO put your openssh private key
        -----END OPENSSH PRIVATE KEY-----
    # Do not perform a host key check for the server. Defaults to "false"
    insecure: "true"
    # Enable git-lfs for this repository. Defaults to "false"
    enableLfs: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: webapp
    namespace: argocd
spec:
    project: default
    source:
        repoURL: git@gitlab.com:Traianik/mypy-terraform.git
        targetRevision: HEAD
        path: mypychart
    destination:
        server: https://kubernetes.default.svc
        namespace: my-application
